name: Test Streamlit Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'streamlit_pipeline/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'streamlit_pipeline/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-cov pytest-mock
        pip install -r streamlit_pipeline/requirements.txt || echo "No requirements.txt found"
    
    - name: Run unit tests
      working-directory: streamlit_pipeline
      run: |
        python run_tests.py --coverage --junit
    
    - name: Run integration tests
      working-directory: streamlit_pipeline
      run: |
        python run_tests.py --integration
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          streamlit_pipeline/test-results.xml
          streamlit_pipeline/htmlcov/
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.python-version == '3.10'
      with:
        file: streamlit_pipeline/.coverage
        flags: streamlit-pipeline
        name: codecov-streamlit-pipeline

  smoke-test:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        pip install -r streamlit_pipeline/requirements.txt || echo "No requirements.txt found"
    
    - name: Run smoke tests
      working-directory: streamlit_pipeline
      run: |
        python run_tests.py --smoke

  performance-test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio pytest-benchmark
        pip install -r streamlit_pipeline/requirements.txt || echo "No requirements.txt found"
    
    - name: Run performance tests
      working-directory: streamlit_pipeline
      run: |
        python run_tests.py --performance
    
    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: streamlit_pipeline/.benchmarks/